name: Gen Docs

on:
  workflow_run:
    workflows: [ "Run Tests" ]
    types: [ completed ]
    branches: [ develop ]
  push:
    branches: [ main ]
    paths:
      - '**.nim*'
      - '**.cfg'
      - '.github/workflows/**'

jobs:
  generate-docs:
    if: |
      ( ${{ github.event.workflow_run.conclusion == 'success' }} &&
        ${{ github.event_name == 'push' }} ) ||
      ( ${{ github.ref_name == 'main' }} )
    # Run when the test workflow happened on a push to develop
    # and it did success ( generate develop docs )
    # ---------- OR ----------
    # When there was a push to main ( generate main docs )
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo's pushed branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          path: source
      - name: Fetch repos's docs branch
        uses: actions/checkout@v3
        with:
          ref: docs
          path: destination
      - name: Install nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: my-dotfiles # Holds the cached flake, so not to build it
      - name: Build docs
        run: |
          cd source
          nix shell -c nimble gendocs ${{ github.ref_name }}
          cd ..
      - name: Move docs to destination
        run: |
          nix shell nixpkgs#rsync -c \
            rsync -a --force source/docs/ destination/${{ github.ref_name }}
      - name: Push docs
        run: |
          cd destination
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "[workflow] Generated ${{ github.ref_name }} docs"
          git push
