name: Run Tests

on:
  push:
    branches-ignore: [ main, docs ]
    paths:
      - '**.nim*'
      - '**.cfg'
      - '.github/workflows/**'
  pull_request:
    branches-ignore: [ main, docs ]
    paths:
      - '**.nim*'
      - '**.cfg'
      - '.github/workflows/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo's pushed branch
        uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: my-dotfiles # Holds the cached flake, so not to build it
      - name: Run tests
        run: |
          nix shell -c nimble test
